# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('institutionid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('contactname', models.CharField(max_length=50)),
                ('contactnumber', models.IntegerField()),
                ('contactemail', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=30)),
                ('secondname', models.CharField(max_length=50)),
                ('age', models.IntegerField(null=True)),
                ('notes', models.CharField(max_length=1000)),
                ('instituitonid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snps.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='Sample2Variant',
            fields=[
                ('sample2variantid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('sampleid', models.AutoField(primary_key=True, serialize=False)),
                ('sequencer', models.CharField(max_length=30)),
                ('sampletype', models.CharField(max_length=30)),
                ('patientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snps.Patient')),
            ],
        ),
        migrations.RemoveField(
            model_name='variant',
            name='change',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='id',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='pathogenic',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='position',
        ),
        migrations.AddField(
            model_name='variant',
            name='cdna',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='gdna',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='gene',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='protein',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='variantid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variant',
            name='chromosome',
            field=models.CharField(max_length=2),
        ),
        migrations.DeleteModel(
            name='Chromosome',
        ),
        migrations.AddField(
            model_name='sample2variant',
            name='sampleid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snps.Samples'),
        ),
        migrations.AddField(
            model_name='sample2variant',
            name='variantid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snps.Variant'),
        ),
    ]
