# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snps', '0002_auto_20170302_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='instituitonid',
        ),
        migrations.AddField(
            model_name='patient',
            name='institutionid',
            field=models.IntegerField(null=True),
        ),
    ]
