# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snps', '0003_auto_20170302_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample2variant',
            name='sampleid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sample2variant',
            name='variantid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='samples',
            name='patientid',
            field=models.IntegerField(null=True),
        ),
    ]
