# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snps', '0004_auto_20170302_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samples',
            name='patientid',
        ),
        migrations.AlterField(
            model_name='patient',
            name='institutionid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snps.Institution'),
        ),
        migrations.AlterField(
            model_name='sample2variant',
            name='sampleid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snps.Samples'),
        ),
        migrations.AlterField(
            model_name='sample2variant',
            name='variantid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snps.Variant'),
        ),
    ]
