# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snps', '0005_auto_20170303_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='samples',
            name='patientid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='snps.Patient'),
            preserve_default=False,
        ),
    ]
